name: hello_app_fix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.6   # <--- taruh disini, jangan di bawah flutter_native_splash

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logosimora1.png

flutter_native_splash:   # <--- ini blok khusus untuk config splash
  color: "#B3E5FC"
  image: lib/assets/logosimora1.png
  android: true
  ios: true
